# Generated by Django 4.1 on 2022-08-14 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prototype', '0003_documents_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='totalchunk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
