# Generated by Django 4.1 on 2022-08-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_documents_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='docfile',
            field=models.CharField(max_length=1000),
        ),
    ]
